### ISSUE TITLE
Don't use the -H and -B flags for specifiying the source and build directory

### ISSUE THREAD

**Issue by dueringa** [ruslo/CGold#21]
In https://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html (and on other pages), the -H. and -B flags are used.

According to http://stackoverflow.com/a/31092052, this is undocumented because it shouldn't be used.  The answer links to https://cmake.org/pipermail/cmake-developers/2016-June/028843.html, it says

```
These are undocumented because they are internal options that
are not meant for public use.
```

So I guess the flags shouldn't be used in the tutorial.

**Comment by ruslo** [comment]
> In https://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html

If you follow `source tree`/`binary tree` link on this page, you will notice [-H](https://cgold.readthedocs.io/en/latest/glossary/-H.html#h) section of glossary with explanation and links. In short I've described my opinion already in this message:
* http://www.mail-archive.com/cmake-developers@cmake.org/msg16748.html

**Comment by dueringa** [comment]
I see, I didn't follow the links to the glossary.

Is there a reason only the `-H` section in the glossary states that it's in internal option? Maybe the `-B` section should at least state that it's undocumented, with a link to the `-H` section for further explanation?

**Comment by ruslo** [comment]
> Maybe the -B section should at least state that it's undocumented, with a link to the -H section for further explanation?

[-B](https://cgold.readthedocs.io/en/latest/glossary/-B.html) has link to [-H](https://cgold.readthedocs.io/en/latest/glossary/-H.html#h) description. And when `-H` first used in document it has a link to glossary:
* https://cgold.readthedocs.io/en/latest/first-step/generate-native-tool/cli-visual-studio.html
* https://cgold.readthedocs.io/en/latest/first-step/generate-native-tool/cli-xcode.html
* https://cgold.readthedocs.io/en/latest/first-step/generate-native-tool/cli-make.html

**Comment by ruslo** [comment]
Closing inactive discussion.
