### ISSUE TITLE
Missing back cover

### ISSUE THREAD

**Issue by wende** [ruslo/CGold#27]
<img width="1122" alt="screen shot 2018-02-06 at 14 57 50" src="https://user-images.githubusercontent.com/4634386/35863198-37385336-0b4e-11e8-8683-84b8669bace5.png">

**Comment by ruslo** [comment]
Done.

I think it fits nice the [First Step](https://cgold.readthedocs.io/en/latest/first-step.html):

![image](https://user-images.githubusercontent.com/4346993/35865470-a67ce358-0b65-11e8-8f49-8baeced5ae1a.png)

😄

**Comment by wende** [comment]
Much better 👍
