### ISSUE TITLE
Enable epub/pdf generation on readthedocs.io

### ISSUE THREAD

**Issue by singalen** [ruslo/CGold#38]
It would be fantastic to be able to download a current version as a epub.
AFAIU, it's something in readthedocs.io project settings.
Thank you.

**Comment by ruslo** [comment]
PDF and EPUB generation enabled:
- https://readthedocs.org/projects/cgold/downloads/pdf/latest/
- https://readthedocs.org/projects/cgold/downloads/epub/latest/
