### ISSUE TITLE
It should be "cmake -S src -B build" instead of "cmake -H src -B build"

### ISSUE THREAD

**Issue by stevenleeS0ht** [ruslo/CGold#40]
in [https://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html](https://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html)

**Comment by ruslo** [comment]
`-S` available since CMake 3.13:
- https://cgold.readthedocs.io/en/latest/glossary/-H.html

Some examples starts with 2.8:
- https://cgold.readthedocs.io/en/latest/tutorials/cmake-stages.html

**Comment by StefanRickli** [comment]
Ah okay, never mind my pull request #42 then.
But do you think adding a brief explanation to the tutorial or glossary on why -H is still used in the tutorial might be beneficial?

**Comment by ruslo** [comment]
> But do you think adding a brief explanation to the tutorial or glossary on why -H is still used in the tutorial might be beneficial?

I think all the details are already there:
- https://cgold.readthedocs.io/en/latest/glossary/-H.html

The new option is available in CMake 3.13, so it's better to wait while it will be more mainstream. I think that the first step should be as simple as possible.
