### ISSUE TITLE
Is it possible to send return value via argument?

### ISSUE THREAD

**Issue by stevenleeS0ht** [ruslo/CGold#41]
In [Return Value](https://cgold.readthedocs.io/en/latest/tutorials/control-structures.html#return-value), it recommends to set a variable to the parent scope to return a value from function.

But I am wondering if it is possible to return a value via argument of function. It is more commonly seen in CMake for example: ProcessorCount(N), N is a output argument of function.

Is the function argument in CMake passed by reference?

**Comment by ruslo** [comment]
> if it is possible to return a value via argument of function

You're passing the name of the variable and in function you set this variable to `PARENT_SCOPE`.

> It is more commonly seen in CMake for example: ProcessorCount(N), N is a output argument of function.

It's not common at all. It can be used for the functions with a trivial signature. Widely used approach is `somefunc(SOMEPARAM somevalue)`. E.g.:
- https://cmake.org/cmake/help/latest/command/install.html
- https://cmake.org/cmake/help/latest/command/add_custom_command.html
- https://cmake.org/cmake/help/latest/command/execute_process.html

> Is the function argument in CMake passed by reference?

There is no such thing in CMake language. It's the same `PARENT_SCOPE`:
- https://github.com/Kitware/CMake/blob/v3.14.4/Modules/ProcessorCount.cmake#L218

**Comment by ruslo** [comment]
Closing inactive discussion.
