### ISSUE TITLE
Wrong source link

### ISSUE THREAD

**Issue by victorshcherbakov** [ruslo/CGold#50]
In this file:
CGold/docs/tutorials/libraries/symbols/tools.rst

The link duplicates:
/examples/library-examples/library-symbols/Boo.cpp

It seems to me, Foo.cpp must be in the second case.

**Comment by ruslo** [comment]
> In this file:
CGold/docs/tutorials/libraries/symbols/tools.rst

For the reference:
- https://cgold.readthedocs.io/en/latest/tutorials/libraries/symbols/tools.html#example

> The link duplicates:
/examples/library-examples/library-symbols/Boo.cpp

It's included twice, but different parts of it highlighted. The first time we show that `Boo::boo` is defined, the second time we show that `Foo::foo` used.

> It seems to me, Foo.cpp must be in the second case.

There is no such file:
- https://github.com/cgold-examples/library-examples/tree/772d0c43b80e08e18c0b55812be1b88addd5753c/library-symbols
